name: ci

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to GitHub registry'
        required: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Build
        run: go build coredns/main.go

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tags
        id: meta
        uses: docker/metadata-action@v4
        flavor: |
          latest=true
        images: |
          terrasim/coredns-traefik
          ghcr.io/terrasim/coredns-traefik
        tags: |
          type=semver,pattern={{major}}
          type=semver,pattern={{major.minor}}
          type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: |
            linux/amd64
            linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # push only to registry if workflow got triggered by tag creation
          push: ${{ github.ref_type == 'tag' || github.event.inputs.publish == 'true' }}
